# Generated by Django 6.0.3 on 2026-04-06 20:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sincronizado', models.BooleanField(default=False)),
                ('status_sincronizacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SINCRONIZADO', 'Sincronizado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('sincronizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('nis', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('identidade_genero', models.CharField(blank=True, max_length=50, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('possui_deficiencia', models.BooleanField(default=False)),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro'), ('CASADO', 'Casado'), ('DIVORCIADO', 'Divorciado'), ('VIUVO', 'Viúvo'), ('UNIAO_ESTAVEL', 'União estável')], max_length=20, null=True)),
                ('autorizacao_uso_imagem', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cidadão',
                'db_table': 'api_cidadao',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sincronizado', models.BooleanField(default=False)),
                ('status_sincronizacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SINCRONIZADO', 'Sincronizado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('sincronizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('rg_orgao', models.CharField(blank=True, max_length=20, null=True)),
                ('rg_uf', models.CharField(blank=True, max_length=2, null=True)),
                ('carteira_trabalho', models.CharField(blank=True, max_length=50, null=True)),
                ('inscricao_eleitoral', models.CharField(blank=True, max_length=30, null=True)),
                ('zona', models.CharField(blank=True, max_length=10, null=True)),
                ('secao', models.CharField(blank=True, max_length=10, null=True)),
                ('cidadao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.cidadao')),
            ],
            options={
                'db_table': 'api_documentos',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sincronizado', models.BooleanField(default=False)),
                ('status_sincronizacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SINCRONIZADO', 'Sincronizado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('sincronizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('logradouro', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('situacao_imovel', models.CharField(blank=True, choices=[('PROPRIA', 'Própria'), ('ALUGADA', 'Alugada'), ('CEDIDA', 'Cedida'), ('TEMPORARIA', 'Temporária')], max_length=20)),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('material_parede', models.CharField(blank=True, max_length=50)),
                ('qtd_comodos', models.IntegerField(default=1)),
                ('possui_luz', models.BooleanField(default=True)),
                ('possui_asfalto', models.BooleanField(default=False)),
                ('possui_lixo', models.BooleanField(default=True)),
                ('abastecimento_agua', models.CharField(blank=True, max_length=100)),
                ('possui_saneamento', models.BooleanField(default=False)),
                ('cidadao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='api.cidadao')),
            ],
            options={
                'db_table': 'api_habitacao',
            },
        ),
        migrations.CreateModel(
            name='FamiliaMembro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sincronizado', models.BooleanField(default=False)),
                ('status_sincronizacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SINCRONIZADO', 'Sincronizado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('sincronizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome_membro', models.CharField(max_length=200)),
                ('parentesco', models.CharField(max_length=50)),
                ('cpf_membro', models.CharField(blank=True, max_length=14, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('escolaridade', models.CharField(blank=True, max_length=100, null=True)),
                ('ocupacao', models.CharField(blank=True, max_length=100, null=True)),
                ('possui_cartao_sus', models.BooleanField(default=True)),
                ('possui_doenca_grave', models.BooleanField(default=False)),
                ('descricao_doenca', models.TextField(blank=True, null=True)),
                ('uso_substancia_ilicita', models.BooleanField(default=False)),
                ('descricao_substancia', models.TextField(blank=True, null=True)),
                ('cidadao_titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_familia', to='api.cidadao')),
            ],
            options={
                'db_table': 'api_familia_membros',
            },
        ),
        migrations.CreateModel(
            name='KeycloakUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycloak_username', models.CharField(blank=True, max_length=150)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keycloak_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Socioeconomico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sincronizado', models.BooleanField(default=False)),
                ('status_sincronizacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SINCRONIZADO', 'Sincronizado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('sincronizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('renda_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precedencia_rendimento', models.TextField(blank=True)),
                ('pessoas_com_rendimento', models.IntegerField(default=0)),
                ('utiliza_servico_social', models.CharField(blank=True, choices=[('PSB', 'PSB'), ('PSEMC', 'PSEMC'), ('PSEAC', 'PSEAC')], max_length=20)),
                ('mais_de_um_nucleo', models.BooleanField(default=False)),
                ('documentacao_completa_grupo', models.BooleanField(default=True)),
                ('observacoes_gerais', models.TextField(blank=True)),
                ('cidadao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socioeconomico', to='api.cidadao')),
            ],
            options={
                'db_table': 'api_socioeconomico',
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sincronizado', models.BooleanField(default=False)),
                ('status_sincronizacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SINCRONIZADO', 'Sincronizado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('sincronizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('EM_ANALISE', 'Em análise'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='EM_ANALISE', max_length=20)),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.beneficio')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios_recebidos', to='api.cidadao')),
            ],
            options={
                'unique_together': {('cidadao', 'beneficio')},
            },
        ),
    ]
