# Generated by Django 6.0.3 on 2026-04-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='status',
            field=models.CharField(choices=[('EM_ANALISE', 'Em análise'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], db_index=True, default='EM_ANALISE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='nome',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='beneficiario',
            index=models.Index(fields=['beneficio', 'status'], name='api_benefic_benefic_286881_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiario',
            index=models.Index(fields=['cidadao', 'status'], name='api_benefic_cidadao_e6166e_idx'),
        ),
    ]
