# Generated by Django 6.0.3 on 2026-04-08 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cidadao_escolaridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='autorizacao_uso_imagem_aceite_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='autorizacao_uso_imagem_responsavel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='abastecimento_agua_outro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familiamembro',
            name='gestante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familiamembro',
            name='possui_deficiencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familiamembro',
            name='qual_deficiencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='beneficio_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='beneficio_tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='beneficio_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='ha_gestante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='ha_pessoa_com_deficiencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='qual_deficiencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='quantidade_adolescentes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='quantidade_adultos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='quantidade_criancas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='quantidade_idosos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='quantidade_pessoas_estudando',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='quantidade_pessoas_residencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='recebe_beneficio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='servicos_sociais',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='abastecimento_agua',
            field=models.CharField(blank=True, choices=[('REDE_PUBLICA', 'Rede pública'), ('POCO', 'Poço'), ('NASCENTE', 'Nascente'), ('CISTERNA', 'Cisterna'), ('CACIMBA', 'Cacimba'), ('OUTRO', 'Outro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomico',
            name='utiliza_servico_social',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TermoResponsabilidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sincronizado', models.BooleanField(default=False)),
                ('status_sincronizacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SINCRONIZADO', 'Sincronizado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('sincronizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome_responsavel', models.CharField(blank=True, max_length=200, null=True)),
                ('local_termo', models.CharField(blank=True, max_length=200, null=True)),
                ('data_termo', models.CharField(blank=True, max_length=20, null=True)),
                ('hora_termo', models.CharField(blank=True, max_length=10, null=True)),
                ('cidadao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termo_responsabilidade', to='api.cidadao')),
            ],
            options={
                'db_table': 'api_termo_responsabilidade',
            },
        ),
    ]
