# Generated by Django 6.0.3 on 2026-04-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cidadao_autorizacao_uso_imagem_aceite_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiamembro',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
