# Generated by Django 6.0.3 on 2026-04-14 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_familiamembro_sexo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiarios_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficios_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cidadaos_atualizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
