# Generated by Django 6.0.3 on 2026-04-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_beneficiario_atualizado_por_beneficio_atualizado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socioeconomico',
            name='cidadao_estava_em_casa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='eh_ribeirinho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='ja_foi_visitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='possui_medida_protetiva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='pretende_voltar_estudar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='violencia_domestica',
            field=models.BooleanField(default=False),
        ),
    ]
