# Generated by Django 6.0.3 on 2026-04-16 02:17

from django.db import migrations, models


def backfill_beneficios_recebidos(apps, schema_editor):
    Socioeconomico = apps.get_model('api', 'Socioeconomico')

    for socioeconomico in Socioeconomico.objects.all().iterator():
        beneficios_recebidos = socioeconomico.beneficios_recebidos or []

        if beneficios_recebidos:
            continue

        if (
            socioeconomico.recebe_beneficio
            and (
                socioeconomico.beneficio_nome
                or socioeconomico.beneficio_tipo
                or socioeconomico.beneficio_valor is not None
            )
        ):
            valor = socioeconomico.beneficio_valor
            socioeconomico.beneficios_recebidos = [
                {
                    'nome': socioeconomico.beneficio_nome,
                    'tipo': socioeconomico.beneficio_tipo,
                    'valor': f'{valor:.2f}' if valor is not None else None,
                    'beneficio_nome': socioeconomico.beneficio_nome,
                    'beneficio_tipo': socioeconomico.beneficio_tipo,
                    'beneficio_valor': f'{valor:.2f}' if valor is not None else None,
                }
            ]
            socioeconomico.save(update_fields=['beneficios_recebidos'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_socioeconomico_cidadao_estava_em_casa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socioeconomico',
            name='beneficios_recebidos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(
            backfill_beneficios_recebidos,
            reverse_code=noop_reverse,
        ),
    ]
