# Generated by Django 6.0.3 on 2026-04-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_socioeconomico_beneficios_recebidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiamembro',
            name='nao_possui_cpf',
            field=models.BooleanField(default=False),
        ),
    ]
