# Generated by Django 5.2.13 on 2026-04-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_escola_codigo_tipo_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycloakuserdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
