# Generated by Django 5.2.13 on 2026-06-30 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_endereco_geocodificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalidadeBeneficiario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('fonte', models.CharField(choices=[('PENDENTE', 'Pendente'), ('GOOGLE', 'Google (revisar)'), ('MANUAL', 'Manual')], default='PENDENTE', max_length=20)),
                ('google_formatted', models.CharField(blank=True, default='', max_length=300)),
                ('google_partial', models.BooleanField(default=False)),
                ('dentro_de_tefe', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_localidade_beneficiario',
                'ordering': ['nome'],
            },
        ),
    ]
