# Generated by Django 5.2.13 on 2026-07-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_socioeconomico_faixa_renda'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='encaminhamentos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='ocupacao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='possui_carteira_trabalho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endereco',
            name='doc_posse_descricao',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='endereco',
            name='iluminacao_publica',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='motivo_terceiros',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='endereco',
            name='possui_doc_posse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endereco',
            name='risco_deslizamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endereco',
            name='risco_enchente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endereco',
            name='risco_inundacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='termoresponsabilidade',
            name='funcao',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
