# Generated by Django 5.2.13 on 2026-07-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_cidadao_encaminhamentos_cidadao_ocupacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='icone',
            field=models.CharField(blank=True, default='VOLUNTEER_ACTIVISM', max_length=50),
        ),
    ]
