# Generated by Django 5.2.13 on 2026-07-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_beneficiario_situacao_cadastro_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='tempo_residencia',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tempo que reside em Tefé'),
        ),
    ]
